name: tencent_trtc_cloud
description: Tencent Real-Time Communication
version: 1.0.5
repository: https://github.com/c1avie/trtc_demo
homepage: https://cloud.tencent.com/document/product/647

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.tencent.trtcplugin
        pluginClass: TRTCCloudPlugin
      ios:
        pluginClass: TencentTRTCCloud
